module Views.Projects exposing (viewProjects)

import Blog exposing (..)
import Html exposing (..)
import Html.Attributes exposing (class)
import Model exposing (..)
import Time exposing (Month(..))


project : String -> String -> Html Msg
project title description =
    div []
        [ h2 [] [ text title ]
        , p []
            [ text (String.filter (\a -> a /= '\n') description |> String.trim)
            ]
        ]


viewProjects : Model -> Html Msg
viewProjects _ =
    div [ class "content-display" ]
        [ h1 [] [ text "Projects" ]
        , p []
            [ text "I am willing to be cosuperviser on Bachelor projects, here "
            , text "are some projects that I have in mind which Troels "
            , text "Henriksen would be the main supervisor for."
            , project "Implement data-parallel lexers in ISPC"
                """
A lexer is a program which identifies lexemes (e.g., keywords, 
identifiers, literals, etc.) which can be used for syntax 
analysis. These lexers are commonly generated by giving a set of 
regular expressions that specify the patterns to be extracted as 
lexemes. These lexers are often implemented in a sequential or 
concurrent manner. We have already implemented a lexer generator which 
generates data-parallel lexers written in CUDA and Futhark, but we are 
not able to generate lexers written in ISPC. ISPC is a data-parallel, 
C-like language which focuses on generating efficient CPU code that 
utilizes SIMD instructions. The goal of this project will be to 
implement such a lexer.
            """
            , project "Dynamic functional array language hash maps"
                """
A hash map is a data structure which stores a set of keys where each 
key maps to a given value. We have implemented static, data-parallel 
hash maps in Futhark, meaning that the set of keys are fixed at a 
given hash map's conception and these hash map can be constructed in 
parallel. These hash maps use the Fredman et al. construction due to 
it being well suited for functional array languages. The goal of the 
project will be to create a hash map which is dynamic such that more 
keys can be inserted. We believe a good idea for this project is to 
use a combination of perfect hashing and open addressing.
            """
            ]
        ]
